//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Booking.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> card_number { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<int> exp_mnth_year { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
    
        public virtual flight flight { get; set; }
        public virtual user user { get; set; }
    }
}
